### ISSUE TITLE
Python syntax highlighting messed up

### ISSUE THREAD

**Issue by dessant** [atom/solarized-light-syntax#21]
https://github.com/atom/solarized-light-syntax/pull/16 mixed the default color map.
Besides most elements having different colors, `self` is not highlighted anymore, nor are keyword arguments, and argument unpacking is not always highlighted either.

If there a way to override the changed defaults without creating a new package?

![1 6](https://cloud.githubusercontent.com/assets/7513068/13889241/29151c14-ed4e-11e5-82bd-d71815f19af0.PNG)

**Comment by dessant** [comment]
Here is the same code with 0.23:
![capture2](https://cloud.githubusercontent.com/assets/7513068/13897115/bad96dee-edad-11e5-9971-ad7b18808c71.PNG)

**Comment by simurai** [comment]
You could try to override the highlighting in your `styles.less` file.

Here some styles that should change it back to be closer to `v0.23.0`. Probably still missing a few things.

```less
// Use v0.23.0 highlighting for Python
.theme-solarized-light-syntax {
  atom-text-editor::shadow .source.python {
    .support.function.builtin,
    .meta.function.parameters {
      color: #657b83;
    }

    .function.magic,
    .constant.language,
    .entity.other,
    .entity.name,
    .entity.name.type.class {
      color: #b58900;
    }

    .variable {
      color: #268bd2;
    }
  }
}
```
